### ISSUE TITLE
Missing JB.Infra.Util dependency/assembly

### ISSUE THREAD

**Issue by fenrhir** [KarateJB/AspNetCore.IdentityServer4.Sample#17]
### Short description
JB.Infra.Util is listed as a required package in both AspNetCore.IdentityServer4.Auth and AspNetCore.IdentityServer4.WebApi but is missing.
Those projects can't be build and many classes refer to the missing assembly.

### Long description
JB.Infra.Util is listed as a required package in both AspNetCore.IdentityServer4.Auth and AspNetCore.IdentityServer4.WebApi but is missing.

#### In AspNetCore.IdentityServer4.Auth project
- AspNetCore.IdentityServer4.Auth.csproj uses JB.Infra.Util version 1.0.0.22 as PackageReference item
- ServiceCollectionExtensions.cs includes a using statement refering to JB.Infra.Service.Redis
- ProfileService includes a using statement refering to JB.Infra.Service.Redis

#### In AspNetCore.IdentityServer4.WebApi project
- AspNetCore.IdentityServer4.WebApi.csproj uses JB.Infra.Util version 1.0.0.22 as PackageReference item
- UserProfileController.cs includes a using statement refering to JB.Infra.Service.Redis
- ServiceCollectionExtensions includes a using statement refering to JB.Infra.Service.Redis

According to the tutorial found [here](https://karatejb.blogspot.com/2019/10/aspnet-core-identity-server-4-role.html), this assembly is used to dynamically load the information to generate Role/Profile Claims from a Redis.

### Possible solutions
Possible solutions implies actions from the repo owner:
- Make JB.Infra.Util available on Github and add link to documentation/tutorials
- Add the required class as .cs files in the solution (maybe within AspNetCore.IdentityServer4.Core project)

### Off-topic
Anyway thank you for the tutorial, who's brought a very interesting perspective on IdentityServer4 :)

**Comment by KarateJB** [comment]
@fenrhir Sorry fot the late, I create a PR for putting the related Cache service into the project :)

[https://github.com/KarateJB/AspNetCore.IdentityServer4.Sample/pull/18](url)
